drop table if exists t_task;
drop table if exists t_user;

create table t_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table t_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

create table t_team (
       	id bigint generated by default as identity,
    	name varchar(255) not null unique,
    	master_id bigint,
        primary key (id)
    );